# Generated by Django 5.0.6 on 2025-04-29 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooddb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='calories',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='carbs',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='fat',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='protein',
            field=models.FloatField(default=0),
        ),
    ]
