# Generated by Django 4.2 on 2025-03-16 16:30

from django.db import migrations, models
import django.db.models.deletion

def add_initial_data(apps, schema_editor):
    Food = apps.get_model('food_detection', 'Food')
    foods = [
        {
            'name': 'Apple',
            'category': 'Fruit',
            'calories': 95,
            'protein': 0.5,
            'carbs': 25,
            'fat': 0.3,
            'food_class': 'apple'
        },
        {
            'name': 'Banana',
            'category': 'Fruit',
            'calories': 105,
            'protein': 1.3,
            'carbs': 27,
            'fat': 0.3,
            'food_class': 'banana'
        }
    ]
    for food_data in foods:
        Food.objects.create(**food_data)

class Migration(migrations.Migration):

    initial = True

    dependencies = []  # Empty dependencies since this is the first migration

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('calories', models.IntegerField()),
                ('protein', models.FloatField()),
                ('carbs', models.FloatField()),
                ('fat', models.FloatField()),
                ('food_class', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DetectionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.FloatField()),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_detection.food')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.RunPython(add_initial_data),
    ]
